# Generated by Django 4.1.3 on 2022-12-01 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created_time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_time"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="username"
                    ),
                ),
                ("password", models.CharField(max_length=256, verbose_name="password")),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="nickname"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatar", verbose_name="avatar"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Normal"), (0, "Deleted")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_super",
                    models.BooleanField(default=False, verbose_name="is_superuser"),
                ),
            ],
            options={
                "db_table": "accounts_user",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created_time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_time"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="username"
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="real_name"
                    ),
                ),
                (
                    "sex",
                    models.SmallIntegerField(
                        choices=[(0, "Prefer not to say"), (1, "Male"), (2, "Female")],
                        default=0,
                        verbose_name="sex",
                    ),
                ),
                (
                    "maxim",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="maxim"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="address"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="accounts.user",
                        verbose_name="related user",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user_profile",
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=128, verbose_name="username")),
                (
                    "login_type",
                    models.CharField(max_length=128, verbose_name="login_type"),
                ),
                ("ip", models.CharField(default="", max_length=32, verbose_name="ip")),
                ("ua", models.CharField(default="", max_length=128, verbose_name="ua")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="login_time"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history_list",
                        to="accounts.user",
                        verbose_name="related user",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_login_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
